// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBY0jeVdbfZPM0d9tB_YzppBdq4X9SVl0',
    appId: '1:799713432632:web:d7256a36b6380ecd1982cd',
    messagingSenderId: '799713432632',
    projectId: 'bus-management-sysem',
    authDomain: 'bus-management-sysem.firebaseapp.com',
    storageBucket: 'bus-management-sysem.appspot.com',
    measurementId: 'G-V8C02CSH8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMs6SBbPeh1pNdyK0fIp2eOtYLz4dm3C0',
    appId: '1:799713432632:android:f1ad60f482e92af81982cd',
    messagingSenderId: '799713432632',
    projectId: 'bus-management-sysem',
    storageBucket: 'bus-management-sysem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgz6aIfIvvmWLA1klfOstaV15J5CUKngg',
    appId: '1:799713432632:ios:876947349d9df53a1982cd',
    messagingSenderId: '799713432632',
    projectId: 'bus-management-sysem',
    storageBucket: 'bus-management-sysem.appspot.com',
    iosClientId: '799713432632-d8t050i4git2vsgnqsnd73p946kfe9gd.apps.googleusercontent.com',
    iosBundleId: 'com.station.busSacco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgz6aIfIvvmWLA1klfOstaV15J5CUKngg',
    appId: '1:799713432632:ios:6b53d07df1c302a41982cd',
    messagingSenderId: '799713432632',
    projectId: 'bus-management-sysem',
    storageBucket: 'bus-management-sysem.appspot.com',
    iosClientId: '799713432632-vb70vhpc37df29ph8p7niiqspqpsmf7j.apps.googleusercontent.com',
    iosBundleId: 'com.station.busSacco.RunnerTests',
  );
}
